---
- name: "Check required pbs.client.exclude dictionary keys"
  fail: msg="exclude.{{ required_key }} must be defined"
  when: required_key not in exclude
  with_items: "{{ required_pbs_exclude_keys }}"
  loop_control:
    loop_var: required_key